import { Auth0Options, auth0 } from "./auth0.mjs";
import { GumroadOptions, gumroad } from "./gumroad.mjs";
import { HubSpotOptions, hubspot } from "./hubspot.mjs";
import { KeycloakOptions, keycloak } from "./keycloak.mjs";
import { LineOptions, line } from "./line.mjs";
import { MicrosoftEntraIdOptions, microsoftEntraId } from "./microsoft-entra-id.mjs";
import { OktaOptions, okta } from "./okta.mjs";
import { PatreonOptions, patreon } from "./patreon.mjs";
import { SlackOptions, slack } from "./slack.mjs";