import { ExtractPluginField, HasRequiredKeys, InferPluginFieldFromTuple, IsAny, OverrideMerge, Prettify, PrettifyDeep, RequiredKeysOf, StripEmptyObjects, UnionToIntersection } from "../../types/helper.mjs";
import { InferInvitation, InferMember, InferOrganization, InferOrganizationRolesFromOption, InferOrganizationZodRolesFromOption, InferTeam, Invitation, InvitationInput, InvitationStatus, Member, MemberInput, Organization, OrganizationInput, OrganizationRole, OrganizationSchema, Team, TeamInput, TeamMember, TeamMemberInput, defaultRolesSchema, invitationSchema, invitationStatus, memberSchema, organizationRoleSchema, organizationSchema, roleSchema, teamMemberSchema, teamSchema } from "../../plugins/organization/schema.mjs";
import { AdminOptions, InferAdminRolesFromOption, SessionWithImpersonatedBy, UserWithRole } from "../../plugins/admin/types.mjs";
import { schema } from "../../plugins/anonymous/schema.mjs";
import { AnonymousOptions, AnonymousSession, UserWithAnonymous } from "../../plugins/anonymous/types.mjs";
import { GenericOAuthConfig, GenericOAuthOptions } from "../../plugins/generic-oauth/types.mjs";
import { Auth0Options, auth0 } from "../../plugins/generic-oauth/providers/auth0.mjs";
import { GumroadOptions, gumroad } from "../../plugins/generic-oauth/providers/gumroad.mjs";
import { HubSpotOptions, hubspot } from "../../plugins/generic-oauth/providers/hubspot.mjs";
import { KeycloakOptions, keycloak } from "../../plugins/generic-oauth/providers/keycloak.mjs";
import { LineOptions, line } from "../../plugins/generic-oauth/providers/line.mjs";
import { MicrosoftEntraIdOptions, microsoftEntraId } from "../../plugins/generic-oauth/providers/microsoft-entra-id.mjs";
import { OktaOptions, okta } from "../../plugins/generic-oauth/providers/okta.mjs";
import { PatreonOptions, patreon } from "../../plugins/generic-oauth/providers/patreon.mjs";
import { SlackOptions, slack } from "../../plugins/generic-oauth/providers/slack.mjs";
import { BaseOAuthProviderOptions } from "../../plugins/generic-oauth/index.mjs";
import { JWKOptions, JWSAlgorithms, Jwk, JwtOptions } from "../../plugins/jwt/types.mjs";
import { AuthorizationQuery, Client, CodeVerificationValue, OAuthAccessToken, OIDCMetadata, OIDCOptions, TokenBody } from "../../plugins/oidc-provider/types.mjs";
import { MULTI_SESSION_ERROR_CODES } from "../../plugins/multi-session/error-codes.mjs";
import { MultiSessionConfig } from "../../plugins/multi-session/index.mjs";
import { OneTimeTokenOptions } from "../../plugins/one-time-token/index.mjs";
import { PhoneNumberOptions, UserWithPhoneNumber } from "../../plugins/phone-number/types.mjs";
import { BackupCodeOptions, backupCode2fa, encodeBackupCodes, generateBackupCodes, getBackupCodes, verifyBackupCode } from "../../plugins/two-factor/backup-codes/index.mjs";
import { OTPOptions, otp2fa } from "../../plugins/two-factor/otp/index.mjs";
import { TOTPOptions, totp2fa } from "../../plugins/two-factor/totp/index.mjs";
import { TwoFactorOptions, TwoFactorProvider, TwoFactorTable, UserWithTwoFactor } from "../../plugins/two-factor/types.mjs";
import { TWO_FACTOR_ERROR_CODES } from "../../plugins/two-factor/error-code.mjs";
import { twoFactorClient } from "../../plugins/two-factor/client.mjs";
import { USERNAME_ERROR_CODES } from "../../plugins/username/error-codes.mjs";
import { ORGANIZATION_ERROR_CODES } from "../../plugins/organization/error-codes.mjs";
import { inferAdditionalFields } from "../../plugins/additional-fields/client.mjs";
import { ADMIN_ERROR_CODES } from "../../plugins/admin/error-codes.mjs";
import { adminClient } from "../../plugins/admin/client.mjs";
import { ANONYMOUS_ERROR_CODES } from "../../plugins/anonymous/error-codes.mjs";
import { anonymousClient } from "../../plugins/anonymous/client.mjs";
import { customSessionClient } from "../../plugins/custom-session/client.mjs";
import { deviceAuthorizationClient } from "../../plugins/device-authorization/client.mjs";
import { EMAIL_OTP_ERROR_CODES } from "../../plugins/email-otp/error-codes.mjs";
import { emailOTPClient } from "../../plugins/email-otp/client.mjs";
import { GENERIC_OAUTH_ERROR_CODES } from "../../plugins/generic-oauth/error-codes.mjs";
import { genericOAuthClient } from "../../plugins/generic-oauth/client.mjs";
import { jwtClient } from "../../plugins/jwt/client.mjs";
import { LastLoginMethodClientConfig, lastLoginMethodClient } from "../../plugins/last-login-method/client.mjs";
import { magicLinkClient } from "../../plugins/magic-link/client.mjs";
import { multiSessionClient } from "../../plugins/multi-session/client.mjs";
import { OidcClientPlugin, oidcClient } from "../../plugins/oidc-provider/client.mjs";
import { GoogleOneTapActionOptions, GoogleOneTapOptions, GsiButtonConfiguration, oneTapClient } from "../../plugins/one-tap/client.mjs";
import { oneTimeTokenClient } from "../../plugins/one-time-token/client.mjs";
import { clientSideHasPermission, inferOrgAdditionalFields, organizationClient } from "../../plugins/organization/client.mjs";
import { PHONE_NUMBER_ERROR_CODES } from "../../plugins/phone-number/error-codes.mjs";
import { phoneNumberClient } from "../../plugins/phone-number/client.mjs";
import { siweClient } from "../../plugins/siwe/client.mjs";
import { usernameClient } from "../../plugins/username/client.mjs";
import { InferServerPlugin } from "./infer-plugin.mjs";
export { ADMIN_ERROR_CODES, ANONYMOUS_ERROR_CODES, AdminOptions, AnonymousOptions, AnonymousSession, Auth0Options, AuthorizationQuery, BackupCodeOptions, BaseOAuthProviderOptions, Client, CodeVerificationValue, EMAIL_OTP_ERROR_CODES, ExtractPluginField, GENERIC_OAUTH_ERROR_CODES, GenericOAuthConfig, GenericOAuthOptions, GoogleOneTapActionOptions, GoogleOneTapOptions, GsiButtonConfiguration, GumroadOptions, HasRequiredKeys, HubSpotOptions, InferAdminRolesFromOption, InferInvitation, InferMember, InferOrganization, InferOrganizationRolesFromOption, InferOrganizationZodRolesFromOption, InferPluginFieldFromTuple, InferServerPlugin, InferTeam, Invitation, InvitationInput, InvitationStatus, IsAny, JWKOptions, JWSAlgorithms, Jwk, JwtOptions, KeycloakOptions, LastLoginMethodClientConfig, LineOptions, MULTI_SESSION_ERROR_CODES, Member, MemberInput, MicrosoftEntraIdOptions, MultiSessionConfig, OAuthAccessToken, OIDCMetadata, OIDCOptions, ORGANIZATION_ERROR_CODES, OTPOptions, OidcClientPlugin, OktaOptions, OneTimeTokenOptions, Organization, OrganizationInput, OrganizationRole, OrganizationSchema, OverrideMerge, PHONE_NUMBER_ERROR_CODES, PatreonOptions, PhoneNumberOptions, Prettify, PrettifyDeep, RequiredKeysOf, SessionWithImpersonatedBy, SlackOptions, StripEmptyObjects, TOTPOptions, TWO_FACTOR_ERROR_CODES, Team, TeamInput, TeamMember, TeamMemberInput, TokenBody, TwoFactorOptions, TwoFactorProvider, TwoFactorTable, USERNAME_ERROR_CODES, UnionToIntersection, UserWithAnonymous, UserWithPhoneNumber, UserWithRole, UserWithTwoFactor, adminClient, anonymousClient, auth0, backupCode2fa, clientSideHasPermission, customSessionClient, defaultRolesSchema, deviceAuthorizationClient, emailOTPClient, encodeBackupCodes, generateBackupCodes, genericOAuthClient, getBackupCodes, gumroad, hubspot, inferAdditionalFields, inferOrgAdditionalFields, invitationSchema, invitationStatus, jwtClient, keycloak, lastLoginMethodClient, line, magicLinkClient, memberSchema, microsoftEntraId, multiSessionClient, oidcClient, okta, oneTapClient, oneTimeTokenClient, organizationClient, organizationRoleSchema, organizationSchema, otp2fa, patreon, phoneNumberClient, roleSchema, schema, siweClient, slack, teamMemberSchema, teamSchema, totp2fa, twoFactorClient, usernameClient, verifyBackupCode };