import { InferOptionSchema, InferPluginErrorCodes } from "../types/plugins.mjs";
import { HIDE_METADATA } from "../utils/hide-metadata.mjs";
import { AccessControl, Role, Statements, SubArray, Subset } from "./access/types.mjs";
import { AuthorizeResponse, createAccessControl, role } from "./access/access.mjs";
import "./access/index.mjs";
import { OrganizationOptions } from "./organization/types.mjs";
import { InferInvitation, InferMember, InferOrganization, InferOrganizationRolesFromOption, InferOrganizationZodRolesFromOption, InferTeam, Invitation, InvitationInput, InvitationStatus, Member, MemberInput, Organization, OrganizationInput, OrganizationRole, OrganizationSchema, Team, TeamInput, TeamMember, TeamMemberInput, defaultRolesSchema, invitationSchema, invitationStatus, memberSchema, organizationRoleSchema, organizationSchema, roleSchema, teamMemberSchema, teamSchema } from "./organization/schema.mjs";
import { getOrgAdapter } from "./organization/adapter.mjs";
import { AdminOptions, InferAdminRolesFromOption, SessionWithImpersonatedBy, UserWithRole } from "./admin/types.mjs";
import { admin } from "./admin/admin.mjs";
import "./admin/index.mjs";
import { AnonymousOptions, AnonymousSession, UserWithAnonymous } from "./anonymous/types.mjs";
import { anonymous } from "./anonymous/index.mjs";
import { ApiKey, ApiKeyOptions } from "./api-key/types.mjs";
import { API_KEY_TABLE_NAME, ERROR_CODES, apiKey, defaultKeyHasher } from "./api-key/index.mjs";
import { BearerOptions, bearer } from "./bearer/index.mjs";
import { BaseCaptchaOptions, CaptchaFoxOptions, CaptchaOptions, CloudflareTurnstileOptions, GoogleRecaptchaOptions, HCaptchaOptions, Provider } from "./captcha/types.mjs";
import { captcha } from "./captcha/index.mjs";
import { CustomSessionPluginOptions, customSession } from "./custom-session/index.mjs";
import { TimeString, ms, sec } from "../utils/time.mjs";
import { DeviceAuthorizationOptions, deviceAuthorization, deviceAuthorizationOptionsSchema } from "./device-authorization/index.mjs";
import { EmailOTPOptions } from "./email-otp/types.mjs";
import { emailOTP } from "./email-otp/index.mjs";
import { GenericOAuthConfig, GenericOAuthOptions } from "./generic-oauth/types.mjs";
import { Auth0Options, auth0 } from "./generic-oauth/providers/auth0.mjs";
import { GumroadOptions, gumroad } from "./generic-oauth/providers/gumroad.mjs";
import { HubSpotOptions, hubspot } from "./generic-oauth/providers/hubspot.mjs";
import { KeycloakOptions, keycloak } from "./generic-oauth/providers/keycloak.mjs";
import { LineOptions, line } from "./generic-oauth/providers/line.mjs";
import { MicrosoftEntraIdOptions, microsoftEntraId } from "./generic-oauth/providers/microsoft-entra-id.mjs";
import { OktaOptions, okta } from "./generic-oauth/providers/okta.mjs";
import { PatreonOptions, patreon } from "./generic-oauth/providers/patreon.mjs";
import { SlackOptions, slack } from "./generic-oauth/providers/slack.mjs";
import { BaseOAuthProviderOptions, genericOAuth } from "./generic-oauth/index.mjs";
import { HaveIBeenPwnedOptions, haveIBeenPwned } from "./haveibeenpwned/index.mjs";
import { JWKOptions, JWSAlgorithms, Jwk, JwtOptions } from "./jwt/types.mjs";
import { getJwtToken, signJWT } from "./jwt/sign.mjs";
import { createJwk, generateExportedKeyPair, toExpJWT } from "./jwt/utils.mjs";
import { verifyJWT } from "./jwt/verify.mjs";
import { jwt } from "./jwt/index.mjs";
import { LastLoginMethodOptions, lastLoginMethod } from "./last-login-method/index.mjs";
import { MagicLinkOptions, magicLink } from "./magic-link/index.mjs";
import { AuthorizationQuery, Client, CodeVerificationValue, OAuthAccessToken, OIDCMetadata, OIDCOptions, TokenBody } from "./oidc-provider/types.mjs";
import { getClient, getMetadata, oidcProvider } from "./oidc-provider/index.mjs";
import { getMCPProtectedResourceMetadata, getMCPProviderMetadata, mcp, oAuthDiscoveryMetadata, oAuthProtectedResourceMetadata, withMcpAuth } from "./mcp/index.mjs";
import { MultiSessionConfig, multiSession } from "./multi-session/index.mjs";
import { OAuthProxyOptions, oAuthProxy } from "./oauth-proxy/index.mjs";
import { OneTapOptions, oneTap } from "./one-tap/index.mjs";
import { OneTimeTokenOptions, oneTimeToken } from "./one-time-token/index.mjs";
import { FieldSchema, OpenAPIModelSchema, Path, generator } from "./open-api/generator.mjs";
import { OpenAPIOptions, openAPI } from "./open-api/index.mjs";
import { PhoneNumberOptions, UserWithPhoneNumber } from "./phone-number/types.mjs";
import { phoneNumber } from "./phone-number/index.mjs";
import { SIWEPluginOptions, siwe } from "./siwe/index.mjs";
import { BackupCodeOptions, backupCode2fa, generateBackupCodes, getBackupCodes, verifyBackupCode } from "./two-factor/backup-codes/index.mjs";
import { OTPOptions, otp2fa } from "./two-factor/otp/index.mjs";
import { TOTPOptions, totp2fa } from "./two-factor/totp/index.mjs";
import { TwoFactorOptions, TwoFactorProvider, TwoFactorTable, UserWithTwoFactor } from "./two-factor/types.mjs";
import { TWO_FACTOR_ERROR_CODES } from "./two-factor/error-code.mjs";
import { twoFactorClient } from "./two-factor/client.mjs";
import { twoFactor } from "./two-factor/index.mjs";
import { USERNAME_ERROR_CODES } from "./username/error-codes.mjs";
import { UsernameOptions, username } from "./username/index.mjs";
import { DefaultOrganizationPlugin, DynamicAccessControlEndpoints, OrganizationCreator, OrganizationEndpoints, OrganizationPlugin, TeamEndpoints, organization, parseRoles } from "./organization/organization.mjs";
import "./organization/index.mjs";
import { AuthEndpoint, AuthMiddleware, createAuthEndpoint, createAuthMiddleware, optionsMiddleware } from "@better-auth/core/api";
export { API_KEY_TABLE_NAME, AccessControl, AdminOptions, AnonymousOptions, AnonymousSession, ApiKey, ApiKeyOptions, Auth0Options, type AuthEndpoint, type AuthMiddleware, AuthorizationQuery, AuthorizeResponse, BackupCodeOptions, BaseCaptchaOptions, BaseOAuthProviderOptions, BearerOptions, CaptchaFoxOptions, CaptchaOptions, Client, CloudflareTurnstileOptions, CodeVerificationValue, CustomSessionPluginOptions, DefaultOrganizationPlugin, DeviceAuthorizationOptions, DynamicAccessControlEndpoints, ERROR_CODES, EmailOTPOptions, FieldSchema, GenericOAuthConfig, GenericOAuthOptions, GoogleRecaptchaOptions, GumroadOptions, HCaptchaOptions, HIDE_METADATA, HaveIBeenPwnedOptions, HubSpotOptions, InferAdminRolesFromOption, InferInvitation, InferMember, InferOptionSchema, InferOrganization, InferOrganizationRolesFromOption, InferOrganizationZodRolesFromOption, InferPluginErrorCodes, InferTeam, Invitation, InvitationInput, InvitationStatus, JWKOptions, JWSAlgorithms, Jwk, JwtOptions, KeycloakOptions, LastLoginMethodOptions, LineOptions, MagicLinkOptions, Member, MemberInput, MicrosoftEntraIdOptions, MultiSessionConfig, OAuthAccessToken, OAuthProxyOptions, OIDCMetadata, OIDCOptions, OTPOptions, OktaOptions, OneTapOptions, OneTimeTokenOptions, OpenAPIModelSchema, OpenAPIOptions, Organization, OrganizationCreator, OrganizationEndpoints, OrganizationInput, OrganizationOptions, OrganizationPlugin, OrganizationRole, OrganizationSchema, Path, PatreonOptions, PhoneNumberOptions, Provider, Role, SIWEPluginOptions, SessionWithImpersonatedBy, SlackOptions, Statements, SubArray, Subset, TOTPOptions, TWO_FACTOR_ERROR_CODES, Team, TeamEndpoints, TeamInput, TeamMember, TeamMemberInput, TimeString, TokenBody, TwoFactorOptions, TwoFactorProvider, TwoFactorTable, USERNAME_ERROR_CODES, UserWithAnonymous, UserWithPhoneNumber, UserWithRole, UserWithTwoFactor, UsernameOptions, admin, anonymous, apiKey, auth0, backupCode2fa, bearer, captcha, createAccessControl, createAuthEndpoint, createAuthMiddleware, createJwk, customSession, defaultKeyHasher, defaultRolesSchema, deviceAuthorization, deviceAuthorizationOptionsSchema, emailOTP, generateBackupCodes, generateExportedKeyPair, generator, genericOAuth, getBackupCodes, getClient, getJwtToken, getMCPProtectedResourceMetadata, getMCPProviderMetadata, getMetadata, getOrgAdapter, gumroad, haveIBeenPwned, hubspot, invitationSchema, invitationStatus, jwt, keycloak, lastLoginMethod, line, magicLink, mcp, memberSchema, microsoftEntraId, ms, multiSession, oAuthDiscoveryMetadata, oAuthProtectedResourceMetadata, oAuthProxy, oidcProvider, okta, oneTap, oneTimeToken, openAPI, optionsMiddleware, organization, organizationRoleSchema, organizationSchema, otp2fa, parseRoles, patreon, phoneNumber, role, roleSchema, sec, signJWT, siwe, slack, teamMemberSchema, teamSchema, toExpJWT, totp2fa, twoFactor, twoFactorClient, username, verifyBackupCode, verifyJWT, withMcpAuth };