#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""修复 routes.py - 添加 ContentGenerator 兜底和 generate_video 接口"""

def main():
    from pathlib import Path

    routes_path = Path("/workspace/api/routes.py")
    content = routes_path.read_text(encoding="utf-8")

    # 新 ContentGenerator：使用列表拼接，避免字符串中的 \n 转义问题
    new_cg_lines = []
    new_cg_lines.append("# ============ ContentGenerator：LLM 不可用时的本地兜底 ============")
    new_cg_lines.append("")
    new_cg_lines.append("class ContentGenerator:")
    new_cg_lines.append('    """不依赖外部 LLM 的中文营销文案生成器。根据 content_type 选择模板填充商品信息。"""')
    new_cg_lines.append("")
    new_cg_lines.append("    _TAG_SETS = {")
    new_cg_lines.append('        "image_text": ["#好物推荐", "#种草笔记", "#品质生活", "#今日推荐"],')
    new_cg_lines.append('        "script": ["#短视频脚本", "#口播", "#好物推荐"],')
    new_cg_lines.append('        "review": ["#深度测评", "#好物测评", "#品质推荐"],')
    new_cg_lines.append('        "plot": ["#剧情植入", "#短剧", "#好物推荐"],')
    new_cg_lines.append('        "compare": ["#对比测评", "#选购指南", "#性价比"],')
    new_cg_lines.append("    }")
    new_cg_lines.append("")
    new_cg_lines.append("    @classmethod")
    new_cg_lines.append("    def _lines(cls, rows):")
    new_cg_lines.append('        return chr(10).join(rows)')
    new_cg_lines.append("")
    new_cg_lines.append("    @classmethod")
    new_cg_lines.append("    def _t_image_text(cls, title, price):")
    new_cg_lines.append("        rows = [")
    new_cg_lines.append('            "\u2728 " + title + "\uff5a姐妹们真的不能错过！'\",)
    new_cg_lines.append('            "'\",)
    new_cg_lines.append('            "\ud83c\udf1f 为什么推荐它？'\",)
    new_cg_lines.append('            "1\ufe0f\u20e3 真的超级好用！用完立刻回购'\",)
    new_cg_lines.append('            "2\ufe0f\u20e3 成分安全温和，敏感肌也完全 OK'\",)
    new_cg_lines.append('            "3\ufe0f\u20e3 性价比超高，学生党也能轻松入手'\",)
    new_cg_lines.append('            "'\",)
    new_cg_lines.append('            "\ud83d\udca1 使用小技巧：'\",)
    new_cg_lines.append('            "每次取适量，轻轻拍打至完全吸收，坚持一个月状态肉眼可见的变好！'\",)
    new_cg_lines.append('            "'\",)
    new_cg_lines.append('            "\ud83d\udcca 使用 28 天后的真实感受：'\",)
    new_cg_lines.append('            "- 水润度 \u2b06\ufe0f 80%'\",)
    new_cg_lines.append('            "- 细腻度 \u2b06\ufe0f 65%'\",)
    new_cg_lines.append('            "- 整体气色 \u2b06\ufe0f 90%'\",)
    new_cg_lines.append('            "'\",)
    new_cg_lines.append('            "姐妹们！真的强烈安利给每一位看到这篇笔记的宝宝~ 早买早享受！\ud83d\udc95'\",)
    new_cg_lines.append("        ]")
    new_cg_lines.append("        return cls._lines(rows)")
    new_cg_lines.append("")
    new_cg_lines.append("    @classmethod")
    new_cg_lines.append("    def _t_script(cls, title, price):")
    new_cg_lines.append("        q = chr(34)  # double quote")
    new_cg_lines.append("        rows = [")
    new_cg_lines.append('            "\u3010开场 3s 抓眼球\u3011'\",)
    new_cg_lines.append('            q + "姐妹们！这个真的是我今年用到最惊艳的东西，没有之一！" + q,',)
    new_cg_lines.append('            "'\",)
    new_cg_lines.append('            "\u3010产品展示\u3011'\",)
    new_cg_lines.append('            "- 镜头对准 " + title,',)
    new_cg_lines.append('            "- 展示核心功能/效果'\",)
    new_cg_lines.append('            "- 对比使用前后'\",)
    new_cg_lines.append('            "'\",)
    new_cg_lines.append('            "\u3010痛点引出\u3011'\",)
    new_cg_lines.append('            q + "之前我一直被这个问题困扰，试了市面上 N 多产品，都没能解决...直到遇到它！" + q,',)
    new_cg_lines.append('            "'\",)
    new_cg_lines.append('            "\u3010核心卖点\u3011'\",)
    new_cg_lines.append('            "\u2705 效果看得见'\",)
    new_cg_lines.append('            "\u2705 价格很亲民 \u00a5" + str(price),',)
    new_cg_lines.append('            "\u2705 大牌同厂'\",)
    new_cg_lines.append('            "\u2705 售后有保障'\",)
    new_cg_lines.append('            "'\",)
    new_cg_lines.append('            "\u3010转化引导\u3011'\",)
    new_cg_lines.append('            q + "真的，我已经回购 3 次了！现在点左下角小黄车，还有限时折扣，错过真的拍大腿！" + q,',)
    new_cg_lines.append('            "'\",)
    new_cg_lines.append('            "\u3010结尾\u3011'\",)
    new_cg_lines.append('            q + "关注我，每天分享真实好用的平价好物~" + q,',)
    new_cg_lines.append("        ]")
    new_cg_lines.append("        return cls._lines(rows)")
    new_cg_lines.append("")
    new_cg_lines.append("    @classmethod")
    new_cg_lines.append("    def _t_review(cls, title, price):")
    new_cg_lines.append("        rows = [")
    new_cg_lines.append('            "\u3010" + title + "\uff5c30 天深度测评\u3011'\",)
    new_cg_lines.append('            "'\",)
    new_cg_lines.append('            "\ud83d\udce6 开箱体验'\",)
    new_cg_lines.append('            "包装非常精致，开箱有仪式感，送礼也很合适'\",)
    new_cg_lines.append('            "'\",)
    new_cg_lines.append('            "\ud83d\udd2c 成分分析'\",)
    new_cg_lines.append('            "- 核心成分：优质原料'\",)
    new_cg_lines.append('            "- 含量充足，足量添加'\",)
    new_cg_lines.append('            "- 无香精酒精防腐剂，敏感肌友好'\",)
    new_cg_lines.append('            "",',')
    new_cg_lines.append('            "\ud83d\udcca 使用效果'\",)
    new_cg_lines.append('            "第 7 天：初体验，吸收很快，不黏腻'\",)
    new_cg_lines.append('            "第 14 天：明显改善，状态稳定'\",)
    new_cg_lines.append('            "第 21 天：惊喜！效果在发光'\",)
    new_cg_lines.append('            "第 30 天：彻底爱上，回购预订'\",)
    new_cg_lines.append('            "'\",)
    new_cg_lines.append('            "\ud83d\udcb0 性价比'\",)
    new_cg_lines.append('            "价格 \u00a5" + str(price) + "，折算下来每天不到几块钱，很划算'\",)
    new_cg_lines.append('            "'\",)
    new_cg_lines.append('            "\u2b50 综合评分：4.8 / 5.0'\",)
    new_cg_lines.append('            "\u2705 推荐购买：追求品质的你、敏感肌易踩雷体质、成分党爱好者'\",)
    new_cg_lines.append("        ]")
    new_cg_lines.append("        return cls._lines(rows)")
    new_cg_lines.append("")
    new_cg_lines.append("    @classmethod")
    new_cg_lines.append("    def _t_compare(cls, title, price):")
    new_cg_lines.append("        rows = [")
    new_cg_lines.append('            "\u3010" + title + " vs 同类产品\uff5c深度对比测评\u3011'\",)
    new_cg_lines.append('            "'\",)
    new_cg_lines.append('            "\u2694\ufe0f 参赛选手'\",)
    new_cg_lines.append('            "A 款：大牌经典款 \u00a5899'\",)
    new_cg_lines.append('            "B 款：网红爆款 \u00a5599'\",)
    new_cg_lines.append('            "C 款：今日主角 \u00a5" + str(price),',)
    new_cg_lines.append('            "'\",)
    new_cg_lines.append('            "\ud83d\udcca 维度对比'\",)
    new_cg_lines.append('            "'\",)
    new_cg_lines.append('            "1\ufe0f\u20e3 成分安全'\",)
    new_cg_lines.append('            "A: \u2b50\u2b50\u2b50\u2b50'\",)
    new_cg_lines.append('            "B: \u2b50\u2b50\u2b50\u2b50'\",)
    new_cg_lines.append('            "C: \u2b50\u2b50\u2b50\u2b50\u2b50 (无香精酒精)'\",)
    new_cg_lines.append('            "'\",)
    new_cg_lines.append('            "2\ufe0f\u20e3 使用感受'\",)
    new_cg_lines.append('            "A: \u2b50\u2b50\u2b50\u2b50 (略油腻)'\",)
    new_cg_lines.append('            "B: \u2b50\u2b50\u2b50 (吸收一般)'\",)
    new_cg_lines.append('            "C: \u2b50\u2b50\u2b50\u2b50\u2b50 (清爽秒吸收)'\",)
    new_cg_lines.append('            "'\",)
    new_cg_lines.append('            "3\ufe0f\u20e3 效果表现'\",)
    new_cg_lines.append('            "A: \u2b50\u2b50\u2b50\u2b50 (1 个月见效)'\",)
    new_cg_lines.append('            "B: \u2b50\u2b50\u2b50 (效果不明显)'\",)
    new_cg_lines.append('            "C: \u2b50\u2b50\u2b50\u2b50\u2b50 (2 周肉眼可见)'\",)
    new_cg_lines.append('            "'\",)
    new_cg_lines.append('            "\ud83c\udfc6 总结'\",)
    new_cg_lines.append('            "综合评分：C > A > B'\",)
    new_cg_lines.append('            "预算充足选 A，追求性价比闭眼入 C！'\",)
    new_cg_lines.append("        ]")
    new_cg_lines.append("        return cls._lines(rows)")
    new_cg_lines.append("")
    new_cg_lines.append("    @classmethod")
    new_cg_lines.append("    def _t_plot(cls, title, price):")
    new_cg_lines.append("        q = chr(34)")
    new_cg_lines.append("        rows = [")
    new_cg_lines.append('            "\u3010场景一：办公室\u00b7日\u00b7内\u3011'\",)
    new_cg_lines.append('            "'\",)
    new_cg_lines.append('            "\uff08小美一脸疲惫地对着电脑\uff09'\",)
    new_cg_lines.append('            "'\",)
    new_cg_lines.append('            "小美：唉，最近加班太多，整个人状态都变差了...'\",)
    new_cg_lines.append('            "'\",)
    new_cg_lines.append('            "同事小丽：\uff08凑近\uff09怎么啦？看起来状态不太好耶'\",)
    new_cg_lines.append('            "'\",)
    new_cg_lines.append('            "小美：最近天天熬夜，试了好多方法都没用'\",)
    new_cg_lines.append('            "'\",)
    new_cg_lines.append('            "同事小丽：\uff08神秘一笑\uff09早说呀！给你推荐我一直在用的神器'\",)
    new_cg_lines.append('            "'\",)
    new_cg_lines.append('            "小美：什么呀？'\",)
    new_cg_lines.append('            "'\",)
    new_cg_lines.append('            "同事小丽：当当当当！就是这个\u2014\u2014" + title + "\uff01'\",)
    new_cg_lines.append('            "'\",)
    new_cg_lines.append('            "\uff08特写产品\uff09'\",)
    new_cg_lines.append('            "'\",)
    new_cg_lines.append('            "同事小丽：我用了 2 个月，你看我现在是不是多了？'\",)
    new_cg_lines.append('            "'\",)
    new_cg_lines.append('            "小美：真的啊！你整个人气色都不一样！'\",)
    new_cg_lines.append('            "'\",)
    new_cg_lines.append('            "同事小丽：真的超好用！成分很温和，关键是效果真的看得见'\",)
    new_cg_lines.append('            "'\",)
    new_cg_lines.append('            "小美：那我也赶紧去买！在哪里下单？'\",)
    new_cg_lines.append('            "'\",)
    new_cg_lines.append('            "同事小丽：点左下角小黄车就可以啦！现在还有限时优惠~'\",)
    new_cg_lines.append('            "'\",)
    new_cg_lines.append('            "\u3010结尾\u3011二人相视一笑，镜头切产品特写 + 购买链接'\",)
    new_cg_lines.append('            "'\",)
    new_cg_lines.append('            "字幕：遇见它，是今年最美丽的意外 \u2728'\",)
    new_cg_lines.append("        ]")
    new_cg_lines.append("        return cls._lines(rows)")
    new_cg_lines.append("")
    new_cg_lines.append("    @classmethod")
    new_cg_lines.append("    def generate(cls, product, content_type, extra_prompt=\"\"):")
    new_cg_lines.append("        title = getattr(product, \"title\", None) or getattr(product, \"name\", \"精选商品\")")
    new_cg_lines.append("        price = getattr(product, \"price\", None) or \"299\"")
    new_cg_lines.append("")
    new_cg_lines.append("        aliases = {")
    new_cg_lines.append('            "image_text": "image_text", "copywriting": "image_text", "\u79cd\u8349": "image_text",')
    new_cg_lines.append('            "script": "script", "\u53e3\u64ad": "script",')
    new_cg_lines.append('            "review": "review", "\u6d4b\u8bc4": "review",')
    new_cg_lines.append('            "plot_script": "plot", "\u5267\u60c5": "plot",')
    new_cg_lines.append('            "compare": "compare", "\u5bf9\u6bd4": "compare",')
    new_cg_lines.append("        }")
    new_cg_lines.append('        key = aliases.get(content_type, "image_text")')
    new_cg_lines.append("")
    new_cg_lines.append('        if key == "image_text":')
    new_cg_lines.append("            body = cls._t_image_text(title, price)")
    new_cg_lines.append('        elif key == "script":')
    new_cg_lines.append("            body = cls._t_script(title, price)")
    new_cg_lines.append('        elif key == "review":')
    new_cg_lines.append("            body = cls._t_review(title, price)")
    new_cg_lines.append('        elif key == "compare":')
    new_cg_lines.append("            body = cls._t_compare(title, price)")
    new_cg_lines.append('        elif key == "plot":')
    new_cg_lines.append("            body = cls._t_plot(title, price)")
    new_cg_lines.append("        else:")
    new_cg_lines.append("            body = cls._t_image_text(title, price)")
    new_cg_lines.append("")
    new_cg_lines.append('        title_out = "\u2728 " + title')
    new_cg_lines.append('        tags = cls._TAG_SETS.get(key, ["#好物推荐", "#种草笔记"])')
    new_cg_lines.append('        call_to_action = "\ud83d\udcac 评论区告诉我你的看法，抽 3 位宝宝送小样~"')
    new_cg_lines.append('        cart_text = "\ud83d\uded2 点击左下角小黄车直接下单 " + title + "，限时优惠 \u00a5" + str(price) + "\uff01"')
    new_cg_lines.append("")
    new_cg_lines.append("        return {")
    new_cg_lines.append('            "title": title_out,')
    new_cg_lines.append('            "body": body,')
    new_cg_lines.append('            "tags": tags,')
    new_cg_lines.append('            "call_to_action": call_to_action,')
    new_cg_lines.append('            "cart_text": cart_text,')
    new_cg_lines.append("        }")
    new_cg_lines.append("")
    new_cg_lines.append("")

    new_cg = "\n".join(new_cg_lines)

    # ===== 修改 generate_content_action =====
    new_gen_content_lines = []
    new_gen_content_lines.append('# ---------- POST /api/actions/generate_content ----------')
    new_gen_content_lines.append('')
    new_gen_content_lines.append('@api_router.post("/api/actions/generate_content")')
    new_gen_content_lines.append('def generate_content_action(body: dict):')
    new_gen_content_lines.append('    """')
    new_gen_content_lines.append('    body: { product_id: int, content_type: string, prompt: string? }')
    new_gen_content_lines.append('    优先调用 LLM 生成；若不可用或超时，则退回本地 ContentGenerator 模板兜底。')
    new_gen_content_lines.append('    """')
    new_gen_content_lines.append('    try:')
    new_gen_content_lines.append('        product_id = body.get("product_id")')
    new_gen_content_lines.append('        content_type = body.get("content_type", "image_text")')
    new_gen_content_lines.append('        extra_prompt = body.get("prompt", "") or ""')
    new_gen_content_lines.append('')
    new_gen_content_lines.append('        if not product_id:')
    new_gen_content_lines.append('            raise HTTPException(status_code=400, detail={"error": "缺少 product_id"})')
    new_gen_content_lines.append('')
    new_gen_content_lines.append('        with get_db() as db:')
    new_gen_content_lines.append('            product = db.query(Product).filter(Product.id == product_id).first()')
    new_gen_content_lines.append('        if not product:')
    new_gen_content_lines.append('            raise HTTPException(status_code=404, detail={"error": "商品 #" + str(product_id) + " 不存在"})')
    new_gen_content_lines.append('')
    new_gen_content_lines.append('        sys.path.insert(0, str(Path(__file__).resolve().parent.parent))')
    new_gen_content_lines.append('')
    new_gen_content_lines.append('        content_obj = None')
    new_gen_content_lines.append('        used_local_fallback = False')
    new_gen_content_lines.append('        llm_error = None')
    new_gen_content_lines.append('')
    new_gen_content_lines.append('        try:')
    new_gen_content_lines.append('            from agents.content_factory import ContentFactory')
    new_gen_content_lines.append('            factory = ContentFactory()')
    new_gen_content_lines.append('')
    new_gen_content_lines.append('            if content_type in ("image_text", "copywriting", "\u79cd\u8349"):')
    new_gen_content_lines.append('                content_obj = factory.generate_xhs_post(product)')
    new_gen_content_lines.append('            elif content_type in ("script", "\u53e3\u64ad"):')
    new_gen_content_lines.append('                result = factory.generate_video_script(product)')
    new_gen_content_lines.append('                if result:')
    new_gen_content_lines.append('                    with get_db() as db2:')
    new_gen_content_lines.append('                        content_obj = db2.query(Content).filter(Content.id == result["content_id"]).first()')
    new_gen_content_lines.append('            elif content_type in ("review", "\u6d4b\u8bc4"):')
    new_gen_content_lines.append('                content_obj = factory.generate_review(product)')
    new_gen_content_lines.append('            elif content_type in ("\u5267\u60c5", "plot_script"):')
    new_gen_content_lines.append('                content_obj = factory.generate_story_script(product)')
    new_gen_content_lines.append('            elif content_type in ("\u5bf9\u6bd4", "compare"):')
    new_gen_content_lines.append('                content_obj = factory.generate_compare(product)')
    new_gen_content_lines.append('            else:')
    new_gen_content_lines.append('                content_obj = factory.generate_xhs_post(product)')
    new_gen_content_lines.append('        except Exception as _e_llm:')
    new_gen_content_lines.append('            llm_error = str(_e_llm)')
    new_gen_content_lines.append('            content_obj = None')
    new_gen_content_lines.append('')
    new_gen_content_lines.append('        if not content_obj:')
    new_gen_content_lines.append('            used_local_fallback = True')
    new_gen_content_lines.append('            local_result = ContentGenerator.generate(product, content_type, extra_prompt)')
    new_gen_content_lines.append('')
    new_gen_content_lines.append('            try:')
    new_gen_content_lines.append('                with get_db() as db3:')
    new_gen_content_lines.append('                    _tags_val = local_result["tags"]')
    new_gen_content_lines.append('                    if isinstance(_tags_val, list):')
    new_gen_content_lines.append('                        _tags_str = ",".join(_tags_val)')
    new_gen_content_lines.append('                    else:')
    new_gen_content_lines.append('                        _tags_str = str(_tags_val)')
    new_gen_content_lines.append('                    new_c = Content(')
    new_gen_content_lines.append('                        product_id=product_id,')
    new_gen_content_lines.append('                        title=local_result["title"],')
    new_gen_content_lines.append('                        body=local_result["body"],')
    new_gen_content_lines.append('                        platform="xhs",')
    new_gen_content_lines.append('                        content_type=content_type,')
    new_gen_content_lines.append('                        tags=_tags_str,')
    new_gen_content_lines.append('                    )')
    new_gen_content_lines.append('                    db3.add(new_c)')
    new_gen_content_lines.append('                    db3.commit()')
    new_gen_content_lines.append('                    db3.refresh(new_c)')
    new_gen_content_lines.append('                    content_obj = new_c')
    new_gen_content_lines.append('            except Exception:')
    new_gen_content_lines.append('                content_obj = None')
    new_gen_content_lines.append('')
    new_gen_content_lines.append('        if content_obj:')
    new_gen_content_lines.append('            _tags = getattr(content_obj, "tags", None)')
    new_gen_content_lines.append('            if isinstance(_tags, str):')
    new_gen_content_lines.append('                _tags_out = [t for t in _tags.split(",") if t]')
    new_gen_content_lines.append('            elif isinstance(_tags, list):')
    new_gen_content_lines.append('                _tags_out = _tags')
    new_gen_content_lines.append('            else:')
    new_gen_content_lines.append('                _tags_out = local_result["tags"] if used_local_fallback else ["#推荐"]')
    new_gen_content_lines.append('')
    new_gen_content_lines.append('            return {')
    new_gen_content_lines.append('                "success": True,')
    new_gen_content_lines.append('                "used_local_fallback": used_local_fallback,')
    new_gen_content_lines.append('                "llm_error": llm_error,')
    new_gen_content_lines.append('                "content": {')
    new_gen_content_lines.append('                    "id": getattr(content_obj, "id", None),')
    new_gen_content_lines.append('                    "title": getattr(content_obj, "title", None) or (local_result["title"] if used_local_fallback else ""),')
    new_gen_content_lines.append('                    "body": getattr(content_obj, "body", None) or (local_result["body"] if used_local_fallback else ""),')
    new_gen_content_lines.append('                    "platform": getattr(content_obj, "platform", "xhs"),')
    new_gen_content_lines.append('                    "content_type": getattr(content_obj, "content_type", content_type),')
    new_gen_content_lines.append('                    "tags": _tags_out,')
    new_gen_content_lines.append('                    "call_to_action": local_result.get("call_to_action") if used_local_fallback else None,')
    new_gen_content_lines.append('                    "cart_text": local_result.get("cart_text") if used_local_fallback else None,')
    new_gen_content_lines.append('                },')
    new_gen_content_lines.append('            }')
    new_gen_content_lines.append('        else:')
    new_gen_content_lines.append('            used_local_fallback = True')
    new_gen_content_lines.append('            local_result = ContentGenerator.generate(product, content_type, extra_prompt)')
    new_gen_content_lines.append('            return {')
    new_gen_content_lines.append('                "success": True,')
    new_gen_content_lines.append('                "used_local_fallback": used_local_fallback,')
    new_gen_content_lines.append('                "llm_error": llm_error,')
    new_gen_content_lines.append('                "content": {')
    new_gen_content_lines.append('                    "id": None,')
    new_gen_content_lines.append('                    "title": local_result["title"],')
    new_gen_content_lines.append('                    "body": local_result["body"],')
    new_gen_content_lines.append('                    "platform": "xhs",')
    new_gen_content_lines.append('                    "content_type": content_type,')
    new_gen_content_lines.append('                    "tags": local_result["tags"],')
    new_gen_content_lines.append('                    "call_to_action": local_result["call_to_action"],')
    new_gen_content_lines.append('                    "cart_text": local_result["cart_text"],')
    new_gen_content_lines.append('                },')
    new_gen_content_lines.append('            }')
    new_gen_content_lines.append('    except HTTPException:')
    new_gen_content_lines.append('        raise')
    new_gen_content_lines.append('    except Exception as e:')
    new_gen_content_lines.append('        logger.error("generate_content_action failed: " + str(e))')
    new_gen_content_lines.append('        raise HTTPException(status_code=500, detail={"error": str(e)})')
    new_gen_content_lines.append('')
    new_gen_content_lines.append('')

    new_gen_content = "\n".join(new_gen_content_lines)

    # ===== 修改 generate_video_action =====
    new_gen_video_lines = []
    new_gen_video_lines.append('# ---------- POST /api/actions/generate_video ----------')
    new_gen_video_lines.append('')
    new_gen_video_lines.append('@api_router.post("/api/actions/generate_video")')
    new_gen_video_lines.append('def generate_video_action(body: dict):')
    new_gen_video_lines.append('    """')
    new_gen_video_lines.append('    body: { product_id: int, template: str, duration: int }')
    new_gen_video_lines.append('    使用 ffmpeg 合成图片轮播视频，没有图片时用 Pillow 生成占位图')
    new_gen_video_lines.append('    """')
    new_gen_video_lines.append('    import shutil')
    new_gen_video_lines.append('    try:')
    new_gen_video_lines.append('        product_id = body.get("product_id")')
    new_gen_video_lines.append('        template = body.get("template", "slideshow")')
    new_gen_video_lines.append('        duration = int(body.get("duration", 8))')
    new_gen_video_lines.append('')
    new_gen_video_lines.append('        if not product_id:')
    new_gen_video_lines.append('            raise HTTPException(status_code=400, detail={"error": "缺少 product_id"})')
    new_gen_video_lines.append('')
    new_gen_video_lines.append('        with get_db() as db:')
    new_gen_video_lines.append('            product = db.query(Product).filter(Product.id == product_id).first()')
    new_gen_video_lines.append('        if not product:')
    new_gen_video_lines.append('            raise HTTPException(status_code=404, detail={"error": "商品 #" + str(product_id) + " 不存在"})')
    new_gen_video_lines.append('')
    new_gen_video_lines.append('        title = product.title or ("商品 #" + str(product_id))')
    new_gen_video_lines.append('')
    new_gen_video_lines.append('        img_dir = Path(Config.IMAGE_DIR) / ("product_" + str(product_id))')
    new_gen_video_lines.append('        img_dir.mkdir(parents=True, exist_ok=True)')
    new_gen_video_lines.append('')
    new_gen_video_lines.append('        existing = []')
    new_gen_video_lines.append('        for suffix in ("*.jpg", "*.jpeg", "*.png"):')
    new_gen_video_lines.append('            existing.extend(sorted(img_dir.glob(suffix)))')
    new_gen_video_lines.append('        existing = existing[:3]')
    new_gen_video_lines.append('')
    new_gen_video_lines.append('        if len(existing) < 3:')
    new_gen_video_lines.append('            try:')
    new_gen_video_lines.append('                from PIL import Image, ImageDraw, ImageFont')
    new_gen_video_lines.append('                for idx in range(3):')
    new_gen_video_lines.append('                    path = img_dir / ("img_" + str(idx) + ".jpg")')
    new_gen_video_lines.append('                    if path.exists() and path in existing:')
    new_gen_video_lines.append('                        continue')
    new_gen_video_lines.append('                    img = Image.new("RGB", (640, 360), (40 + idx * 40, 80 + idx * 30, 140 + idx * 20))')
    new_gen_video_lines.append('                    draw = ImageDraw.Draw(img)')
    new_gen_video_lines.append('                    text = title + " - Scene " + str(idx + 1)')
    new_gen_video_lines.append('                    try:')
    new_gen_video_lines.append('                        font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 22)')
    new_gen_video_lines.append('                    except Exception:')
    new_gen_video_lines.append('                        font = ImageFont.load_default()')
    new_gen_video_lines.append('                    draw.text((20, 160), text, fill=(255, 255, 255), font=font)')
    new_gen_video_lines.append('                    img.save(path, "JPEG", quality=90)')
    new_gen_video_lines.append('                    existing.append(path)')
    new_gen_video_lines.append('            except Exception:')
    new_gen_video_lines.append('                for idx in range(3):')
    new_gen_video_lines.append('                    path = img_dir / ("img_" + str(idx) + ".jpg")')
    new_gen_video_lines.append('                    with open(path, "wb") as _ff:')
    new_gen_video_lines.append('                        _ff.write(bytes.fromhex("ffd8ffe000104a46494600010101006000600000ffdb004300080606070605080707070909080a0c140d0c0b0b0c1912130f141d1a1f1e1d1a1c1c20242e2720222c231c1c2837292c30313434341f27393d38323c2e333432ffc00011080001000101011100ffc40014000100000000000000000000000000000000000000ffc400141001000000000000000000000000000000000000000000ffda000c03010002110311003f00f9c000ffd9"))')
    new_gen_video_lines.append('                    existing.append(path)')
    new_gen_video_lines.append('')
    new_gen_video_lines.append('        if hasattr(Config, "VIDEO_DIR"):')
    new_gen_video_lines.append('            video_dir = Path(Config.VIDEO_DIR) / ("product_" + str(product_id))')
    new_gen_video_lines.append('        else:')
    new_gen_video_lines.append('            video_dir = Path(__file__).resolve().parent.parent / "output" / "videos" / ("product_" + str(product_id))')
    new_gen_video_lines.append('        video_dir.mkdir(parents=True, exist_ok=True)')
    new_gen_video_lines.append('        out_path = video_dir / ("task_" + datetime.now().strftime("%Y%m%d_%H%M%S") + ".mp4")')
    new_gen_video_lines.append('')
    new_gen_video_lines.append('        concat_txt = video_dir / ("concat_" + str(product_id) + ".txt")')
    new_gen_video_lines.append('        with open(concat_txt, "w", encoding="utf-8") as _cf:')
    new_gen_video_lines.append('            for p in existing:')
    new_gen_video_lines.append('                _s = str(p).replace(chr(39), chr(39) + chr(92) + chr(39) + chr(39))')
    new_gen_video_lines.append('                _cf.write("file " + chr(39) + _s + chr(39) + chr(10))')
    new_gen_video_lines.append('                _cf.write("duration 2" + chr(10))')
    new_gen_video_lines.append('')
    new_gen_video_lines.append('        video_url = None')
    new_gen_video_lines.append('        thumb_url = None')
    new_gen_video_lines.append('        tried_ffmpeg = False')
    new_gen_video_lines.append('        ffmpeg_error = None')
    new_gen_video_lines.append('')
    new_gen_video_lines.append('        ffmpeg_path = shutil.which("ffmpeg")')
    new_gen_video_lines.append('        if ffmpeg_path:')
    new_gen_video_lines.append('            tried_ffmpeg = True')
    new_gen_video_lines.append('            try:')
    new_gen_video_lines.append('                cmd = [')
    new_gen_video_lines.append('                    ffmpeg_path, "-y", "-hide_banner", "-loglevel", "error",')
    new_gen_video_lines.append('                    "-f", "concat", "-safe", "0", "-i", str(concat_txt),')
    new_gen_video_lines.append('                    "-pix_fmt", "yuv420p", "-vcodec", "libx264", "-r", "30",')
    new_gen_video_lines.append('                    str(out_path),')
    new_gen_video_lines.append('                ]')
    new_gen_video_lines.append('                proc = subprocess.run(cmd, capture_output=True, text=True, timeout=120)')
    new_gen_video_lines.append('                if proc.returncode == 0 and out_path.exists() and out_path.stat().st_size > 0:')
    new_gen_video_lines.append('                    video_url = "/videos/product_" + str(product_id) + "/" + out_path.name')
    new_gen_video_lines.append('                    thumb_url = "/images/product_" + str(product_id) + "/img_0.jpg"')
    new_gen_video_lines.append('                else:')
    new_gen_video_lines.append('                    ffmpeg_error = proc.stderr or "ffmpeg no output"')
    new_gen_video_lines.append('            except Exception as _e_ffmpeg:')
    new_gen_video_lines.append('                ffmpeg_error = str(_e_ffmpeg)')
    new_gen_video_lines.append('')
    new_gen_video_lines.append('        if not video_url:')
    new_gen_video_lines.append('            video_url = "/images/product_" + str(product_id) + "/img_0.jpg"')
    new_gen_video_lines.append('            thumb_url = "/images/product_" + str(product_id) + "/img_0.jpg"')
    new_gen_video_lines.append('')
    new_gen_video_lines.append('        return {')
    new_gen_video_lines.append('            "success": True,')
    new_gen_video_lines.append('            "video_url": video_url,')
    new_gen_video_lines.append('            "thumbnail": thumb_url,')
    new_gen_video_lines.append('            "duration": duration,')
    new_gen_video_lines.append('            "product_title": title,')
    new_gen_video_lines.append('            "template": template,')
    new_gen_video_lines.append('            "used_ffmpeg": tried_ffmpeg and (ffmpeg_error is None),')
    new_gen_video_lines.append('            "ffmpeg_error": ffmpeg_error,')
    new_gen_video_lines.append('        }')
    new_gen_video_lines.append('    except HTTPException:')
    new_gen_video_lines.append('        raise')
    new_gen_video_lines.append('    except Exception as e:')
    new_gen_video_lines.append('        logger.error("generate_video_action failed: " + str(e))')
    new_gen_video_lines.append('        raise HTTPException(status_code=500, detail={"error": str(e)})')
    new_gen_video_lines.append('')

    new_gen_video = "\n".join(new_gen_video_lines)

    # ===== 现在做替换 =====
    # 1) 删除旧的 generate_content_action
    # 从 '@api_router.post("/api/actions/generate_content")' 到下一个以 '# ----------' 或 '# ===========' 开头的行
    lines = content.split("\n")
    result_lines = []
    i = 0
    n = len(lines)
    inserted_cg = False
    while i < n:
        if 'actions/generate_content' in lines[i] and '@api_router' in lines[i]:
            # 跳过旧函数，直到遇到新的顶层标记或空行后的新定义
            j = i + 1
            while j < n:
                stripped = lines[j].strip()
                if stripped.startswith('# ----------') or stripped.startswith('# ===========') or (stripped.startswith('@api_router') and j > i + 2):
                    break
                j += 1
            # 插入新的 generate_content_action
            if not inserted_cg:
                result_lines.append(new_cg.rstrip("\n"))
                inserted_cg = True
            result_lines.append("")
            result_lines.append(new_gen_content.rstrip("\n"))
            i = j
            continue
        elif 'def generate_content_action' in lines[i] and result_lines and 'generate_content' not in "\n".join(result_lines[-5:]):
            # 防御：如果只遇到 def 没遇到装饰器，也跳过
            j = i + 1
            while j < n:
                stripped = lines[j].strip()
                if stripped.startswith('# ----------') or stripped.startswith('# ===========') or (stripped.startswith('@api_router') and j > i + 2):
                    break
                j += 1
            if not inserted_cg:
                result_lines.append(new_cg.rstrip("\n"))
                inserted_cg = True
            result_lines.append("")
            result_lines.append(new_gen_content.rstrip("\n"))
            i = j
            continue
        else:
            result_lines.append(lines[i])
            i += 1

    if not inserted_cg:
        result_lines.append("")
        result_lines.append(new_cg.rstrip("\n"))
        result_lines.append("")
        result_lines.append(new_gen_content.rstrip("\n"))

    # 2) 插入 generate_video_action（在文件末尾或某个标记处）
    joined = "\n".join(result_lines)
    if 'def generate_video_action' not in joined:
        joined = joined.rstrip() + "\n\n" + new_gen_video.rstrip("\n") + "\n"

    routes_path.write_text(joined, encoding="utf-8")

    # 语法检查
    import ast
    try:
        ast.parse(joined)
        print("[OK] routes.py 修改成功，AST 语法检查通过")
        print("  - ContentGenerator 已插入")
        print("  - generate_content_action 带本地兜底")
        print("  - generate_video_action 已新增")
        import os
        print("  - 文件大小:", os.path.getsize(str(routes_path)), "bytes")
    except SyntaxError as e:
        print("[FAIL] 语法错误:", e)
        print("行号:", e.lineno)
        print("周围代码:")
        around = joined.split("\n")
        start = max(0, e.lineno - 3)
        end = min(len(around), e.lineno + 3)
        for k in range(start, end):
            print("  L" + str(k + 1) + ": " + around[k])
        raise

if __name__ == "__main__":
    main()
