#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""修复 routes.py - 极简版"""
import sys
from pathlib import Path

NL = chr(10)  # newline
DQ = chr(34)  # double quote
SQ = chr(39)  # single quote
BS = chr(92)  # backslash

def line(s):
    return s

# ---------- ContentGenerator class，用 list 拼接，避免字符串嵌套 ----------
CG = []
CG.append('class ContentGenerator:')
CG.append('    _TAG_SETS = {')
CG.append('        "image_text": ["#好物推荐", "#种草笔记", "#品质生活", "#今日推荐"],')
CG.append('        "script": ["#短视频脚本", "#口播", "#好物推荐"],')
CG.append('        "review": ["#深度测评", "#好物测评", "#品质推荐"],')
CG.append('        "plot": ["#剧情植入", "#短剧", "#好物推荐"],')
CG.append('        "compare": ["#对比测评", "#选购指南", "#性价比"],')
CG.append('    }')
CG.append('')
CG.append('    @classmethod')
CG.append('    def _t_image_text(cls, title, price):')
CG.append('        return (')
CG.append('            "\u2728 " + title + "\uff5a姐妹们真的不能错过！" + chr(10) + chr(10)')
CG.append('            "\ud83c\udf1f 为什么推荐它？" + chr(10)')
CG.append('            "1\ufe0f\u20e3 真的超级好用！用完立刻回购" + chr(10)')
CG.append('            "2\ufe0f\u20e3 成分安全温和，敏感肌也完全 OK" + chr(10)')
CG.append('            "3\ufe0f\u20e3 性价比超高，学生党也能轻松入手" + chr(10) + chr(10)')
CG.append('            "\ud83d\udca1 使用小技巧：每次取适量，轻轻拍打至完全吸收，坚持一个月状态肉眼可见的变好！" + chr(10) + chr(10)')
CG.append('            "\ud83d\udcca 使用 28 天后的真实感受：水润度 \u2b06\ufe0f 80%，细腻度 \u2b06\ufe0f 65%，整体气色 \u2b06\ufe0f 90%" + chr(10) + chr(10)')
CG.append('            "姐妹们！真的强烈安利给每一位看到这篇笔记的宝宝~ 早买早享受！\ud83d\udc95"')
CG.append('        )')
CG.append('')
CG.append('    @classmethod')
CG.append('    def _t_script(cls, title, price):')
CG.append('        q = chr(34)')
CG.append('        return (')
CG.append('            "\u3010开场 3s 抓眼球\u3011" + chr(10)')
CG.append('            + q + "姐妹们！这个真的是我今年用到最惊艳的东西，没有之一！" + q + chr(10) + chr(10)')
CG.append('            + "\u3010产品展示\u3011" + chr(10)')
CG.append('            + "- 镜头对准 " + title + chr(10)')
CG.append('            + "- 展示核心功能和效果" + chr(10) + chr(10)')
CG.append('            + "\u3010核心卖点\u3011" + chr(10)')
CG.append('            + "\u2705 效果看得见" + chr(10)')
CG.append('            + "\u2705 价格很亲民 \u00a5" + str(price) + chr(10)')
CG.append('            + "\u2705 大牌同厂" + chr(10) + chr(10)')
CG.append('            + q + "真的，我已经回购 3 次了！现在点左下角小黄车，还有限时折扣！" + q + chr(10) + chr(10)')
CG.append('            + q + "关注我，每天分享真实好用的平价好物~" + q')
CG.append('        )')
CG.append('')
CG.append('    @classmethod')
CG.append('    def _t_review(cls, title, price):')
CG.append('        return (')
CG.append('            "\u3010" + title + " | 30 天深度测评\u3011" + chr(10) + chr(10)')
CG.append('            + "\ud83d\udce6 开箱体验：包装非常精致，开箱有仪式感，送礼也很合适" + chr(10) + chr(10)')
CG.append('            + "\ud83d\udd2c 成分分析：核心成分优质原料，含量充足，无香精酒精防腐剂" + chr(10) + chr(10)')
CG.append('            + "\ud83d\udcca 使用效果：第 7 天吸收很快；第 14 天明显改善；第 21 天惊喜；第 30 天彻底爱上" + chr(10) + chr(10)')
CG.append('            + "\ud83d\udcb0 性价比：价格 \u00a5" + str(price) + "，折算每天不到几块钱" + chr(10) + chr(10)')
CG.append('            + "\u2b50 综合评分：4.8 / 5.0，推荐给追求品质的你"')
CG.append('        )')
CG.append('')
CG.append('    @classmethod')
CG.append('    def _t_compare(cls, title, price):')
CG.append('        return (')
CG.append('            "\u3010" + title + " vs 同类产品 | 深度对比测评\u3011" + chr(10) + chr(10)')
CG.append('            + "A 款：大牌经典款 \u00a5899 | B 款：网红爆款 \u00a5599 | C 款：今日主角 \u00a5" + str(price) + chr(10) + chr(10)')
CG.append('            + "成分安全：A \u2b50\u2b50\u2b50\u2b50 | B \u2b50\u2b50\u2b50\u2b50 | C \u2b50\u2b50\u2b50\u2b50\u2b50" + chr(10)')
CG.append('            + "使用感受：A 略油腻 | B 吸收一般 | C 清爽秒吸收" + chr(10)')
CG.append('            + "效果表现：A 1 个月见效 | B 不明显 | C 2 周肉眼可见" + chr(10) + chr(10)')
CG.append('            + "\ud83c\udfc6 总结：综合评分 C > A > B，追求性价比闭眼入 C！"')
CG.append('        )')
CG.append('')
CG.append('    @classmethod')
CG.append('    def _t_plot(cls, title, price):')
CG.append('        return (')
CG.append('            "\u3010场景一：办公室\u3011" + chr(10)')
CG.append('            + "小美：唉，最近加班太多，状态都变差了..." + chr(10)')
CG.append('            + "同事小丽：怎么啦？看起来状态不太好耶" + chr(10)')
CG.append('            + "小美：天天熬夜，试了好多方法都没用" + chr(10)')
CG.append('            + "同事小丽：早说呀！给你推荐我一直在用的神器" + chr(10)')
CG.append('            + "小美：什么呀？" + chr(10)')
CG.append('            + "同事小丽：当当当当！就是这个\u2014\u2014" + title + "！" + chr(10)')
CG.append('            + "同事小丽：我用了 2 个月，你看我现在是不是多了？" + chr(10)')
CG.append('            + "小美：真的啊！你整个人气色都不一样！" + chr(10)')
CG.append('            + "同事小丽：成分很温和，效果真的看得见" + chr(10)')
CG.append('            + "小美：那我也赶紧去买！在哪里下单？" + chr(10)')
CG.append('            + "同事小丽：点左下角小黄车就可以啦！现在还有限时优惠~" + chr(10)')
CG.append('            + "\u3010结尾\u3011二人相视一笑，镜头切产品特写 + 购买链接" + chr(10)')
CG.append('            + "遇见它，是今年最美丽的意外 \u2728"')
CG.append('        )')
CG.append('')
CG.append('    @classmethod')
CG.append('    def generate(cls, product, content_type, extra_prompt=""):')
CG.append('        title = getattr(product, "title", None) or getattr(product, "name", "精选商品")')
CG.append('        price = getattr(product, "price", None) or "299"')
CG.append('        aliases = {')
CG.append('            "image_text": "image_text", "copywriting": "image_text", "\u79cd\u8349": "image_text",')
CG.append('            "script": "script", "\u53e3\u64ad": "script",')
CG.append('            "review": "review", "\u6d4b\u8bc4": "review",')
CG.append('            "plot_script": "plot", "\u5267\u60c5": "plot",')
CG.append('            "compare": "compare", "\u5bf9\u6bd4": "compare",')
CG.append('        }')
CG.append('        key = aliases.get(content_type, "image_text")')
CG.append('        if key == "image_text":')
CG.append('            body = cls._t_image_text(title, price)')
CG.append('        elif key == "script":')
CG.append('            body = cls._t_script(title, price)')
CG.append('        elif key == "review":')
CG.append('            body = cls._t_review(title, price)')
CG.append('        elif key == "compare":')
CG.append('            body = cls._t_compare(title, price)')
CG.append('        elif key == "plot":')
CG.append('            body = cls._t_plot(title, price)')
CG.append('        else:')
CG.append('            body = cls._t_image_text(title, price)')
CG.append('        title_out = "\u2728 " + title')
CG.append('        tags = cls._TAG_SETS.get(key, ["#好物推荐"])')
CG.append('        call_to_action = "\ud83d\udcac 评论区告诉我你的看法，抽 3 位宝宝送小样~"')
CG.append('        cart_text = "\ud83d\uded2 点击左下角小黄车下单 " + title + "，限时优惠 \u00a5" + str(price) + "！"')
CG.append('        return {"title": title_out, "body": body, "tags": tags, "call_to_action": call_to_action, "cart_text": cart_text}')

CONTENT_GENERATOR = NL.join(CG)

# 语法检查
import ast
try:
    ast.parse(CONTENT_GENERATOR)
    print("[OK] ContentGenerator 语法检查通过")
except SyntaxError as e:
    print("[FAIL] ContentGenerator:", e)
    sys.exit(1)

# ---------- generate_content_action (with fallback) ----------
GC = []
GC.append('@api_router.post("/api/actions/generate_content")')
GC.append('def generate_content_action(body: dict):')
GC.append('    try:')
GC.append('        product_id = body.get("product_id")')
GC.append('        content_type = body.get("content_type", "image_text")')
GC.append('        extra_prompt = body.get("prompt", "") or ""')
GC.append('        if not product_id:')
GC.append('            raise HTTPException(status_code=400, detail={"error": "缺少 product_id"})')
GC.append('        with get_db() as db:')
GC.append('            product = db.query(Product).filter(Product.id == product_id).first()')
GC.append('        if not product:')
GC.append('            raise HTTPException(status_code=404, detail={"error": "商品 #" + str(product_id) + " 不存在"})')
GC.append('        sys.path.insert(0, str(Path(__file__).resolve().parent.parent))')
GC.append('        content_obj = None')
GC.append('        used_local_fallback = False')
GC.append('        llm_error = None')
GC.append('        try:')
GC.append('            from agents.content_factory import ContentFactory')
GC.append('            factory = ContentFactory()')
GC.append('            if content_type in ("image_text", "copywriting", "\u79cd\u8349"):')
GC.append('                content_obj = factory.generate_xhs_post(product)')
GC.append('            elif content_type in ("script", "\u53e3\u64ad"):')
GC.append('                result = factory.generate_video_script(product)')
GC.append('                if result:')
GC.append('                    with get_db() as db2:')
GC.append('                        content_obj = db2.query(Content).filter(Content.id == result["content_id"]).first()')
GC.append('            elif content_type in ("review", "\u6d4b\u8bc4"):')
GC.append('                content_obj = factory.generate_review(product)')
GC.append('            elif content_type in ("\u5267\u60c5", "plot_script"):')
GC.append('                content_obj = factory.generate_story_script(product)')
GC.append('            elif content_type in ("\u5bf9\u6bd4", "compare"):')
GC.append('                content_obj = factory.generate_compare(product)')
GC.append('            else:')
GC.append('                content_obj = factory.generate_xhs_post(product)')
GC.append('        except Exception as _e_llm:')
GC.append('            llm_error = str(_e_llm)')
GC.append('            content_obj = None')
GC.append('        local_result = None')
GC.append('        if not content_obj:')
GC.append('            used_local_fallback = True')
GC.append('            local_result = ContentGenerator.generate(product, content_type, extra_prompt)')
GC.append('            try:')
GC.append('                with get_db() as db3:')
GC.append('                    _tags_val = local_result["tags"]')
GC.append('                    _tags_str = ",".join(_tags_val) if isinstance(_tags_val, list) else str(_tags_val)')
GC.append('                    new_c = Content(product_id=product_id, title=local_result["title"], body=local_result["body"], platform="xhs", content_type=content_type, tags=_tags_str)')
GC.append('                    db3.add(new_c); db3.commit(); db3.refresh(new_c)')
GC.append('                    content_obj = new_c')
GC.append('            except Exception:')
GC.append('                content_obj = None')
GC.append('        if content_obj:')
GC.append('            _tags = getattr(content_obj, "tags", None)')
GC.append('            if isinstance(_tags, str):')
GC.append('                _tags_out = [t for t in _tags.split(",") if t]')
GC.append('            elif isinstance(_tags, list):')
GC.append('                _tags_out = _tags')
GC.append('            else:')
GC.append('                _tags_out = local_result["tags"] if used_local_fallback and local_result else ["#推荐"]')
GC.append('            return {')
GC.append('                "success": True,')
GC.append('                "used_local_fallback": used_local_fallback,')
GC.append('                "llm_error": llm_error,')
GC.append('                "content": {')
GC.append('                    "id": getattr(content_obj, "id", None),')
GC.append('                    "title": getattr(content_obj, "title", None) or (local_result["title"] if used_local_fallback and local_result else ""),')
GC.append('                    "body": getattr(content_obj, "body", None) or (local_result["body"] if used_local_fallback and local_result else ""),')
GC.append('                    "platform": getattr(content_obj, "platform", "xhs"),')
GC.append('                    "content_type": getattr(content_obj, "content_type", content_type),')
GC.append('                    "tags": _tags_out,')
GC.append('                    "call_to_action": local_result.get("call_to_action") if used_local_fallback and local_result else None,')
GC.append('                    "cart_text": local_result.get("cart_text") if used_local_fallback and local_result else None,')
GC.append('                },')
GC.append('            }')
GC.append('        else:')
GC.append('            used_local_fallback = True')
GC.append('            local_result = ContentGenerator.generate(product, content_type, extra_prompt)')
GC.append('            return {')
GC.append('                "success": True,')
GC.append('                "used_local_fallback": used_local_fallback,')
GC.append('                "llm_error": llm_error,')
GC.append('                "content": {')
GC.append('                    "id": None, "title": local_result["title"], "body": local_result["body"],')
GC.append('                    "platform": "xhs", "content_type": content_type, "tags": local_result["tags"],')
GC.append('                    "call_to_action": local_result["call_to_action"], "cart_text": local_result["cart_text"],')
GC.append('                },')
GC.append('            }')
GC.append('    except HTTPException:')
GC.append('        raise')
GC.append('    except Exception as e:')
GC.append('        logger.error("generate_content_action failed: " + str(e))')
GC.append('        raise HTTPException(status_code=500, detail={"error": str(e)})')

GENERATE_CONTENT = NL.join(GC)

try:
    ast.parse(GENERATE_CONTENT)
    print("[OK] generate_content_action 语法检查通过")
except SyntaxError as e:
    print("[FAIL] generate_content_action:", e, "行号:", e.lineno)
    around = GENERATE_CONTENT.split(NL)
    for k in range(max(0, e.lineno-3), min(len(around), e.lineno+2)):
        print("  L" + str(k+1) + ": " + around[k])
    sys.exit(1)

# ---------- generate_video_action ----------
GV = []
GV.append('@api_router.post("/api/actions/generate_video")')
GV.append('def generate_video_action(body: dict):')
GV.append('    import shutil')
GV.append('    try:')
GV.append('        product_id = body.get("product_id")')
GV.append('        template = body.get("template", "slideshow")')
GV.append('        duration = int(body.get("duration", 8))')
GV.append('        if not product_id:')
GV.append('            raise HTTPException(status_code=400, detail={"error": "缺少 product_id"})')
GV.append('        with get_db() as db:')
GV.append('            product = db.query(Product).filter(Product.id == product_id).first()')
GV.append('        if not product:')
GV.append('            raise HTTPException(status_code=404, detail={"error": "商品 #" + str(product_id) + " 不存在"})')
GV.append('        title = product.title or ("商品 #" + str(product_id))')
GV.append('        img_dir = Path(Config.IMAGE_DIR) / ("product_" + str(product_id))')
GV.append('        img_dir.mkdir(parents=True, exist_ok=True)')
GV.append('        existing = []')
GV.append('        for suffix in ("*.jpg", "*.jpeg", "*.png"):')
GV.append('            existing.extend(sorted(img_dir.glob(suffix)))')
GV.append('        existing = existing[:3]')
GV.append('        if len(existing) < 3:')
GV.append('            try:')
GV.append('                from PIL import Image, ImageDraw, ImageFont')
GV.append('                for idx in range(3):')
GV.append('                    path = img_dir / ("img_" + str(idx) + ".jpg")')
GV.append('                    if path.exists() and path in existing:')
GV.append('                        continue')
GV.append('                    img = Image.new("RGB", (640, 360), (40 + idx * 40, 80 + idx * 30, 140 + idx * 20))')
GV.append('                    draw = ImageDraw.Draw(img)')
GV.append('                    text = title + " - Scene " + str(idx + 1)')
GV.append('                    try:')
GV.append('                        font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 22)')
GV.append('                    except Exception:')
GV.append('                        font = ImageFont.load_default()')
GV.append('                    draw.text((20, 160), text, fill=(255, 255, 255), font=font)')
GV.append('                    img.save(path, "JPEG", quality=90)')
GV.append('                    existing.append(path)')
GV.append('            except Exception:')
GV.append('                for idx in range(3):')
GV.append('                    path = img_dir / ("img_" + str(idx) + ".jpg")')
GV.append('                    with open(path, "wb") as _fh:')
GV.append('                        _fh.write(bytes.fromhex("ffd8ffe000104a46494600010101006000600000ffdb004300080606070605080707070909080a0c140d0c0b0b0c1912130f141d1a1f1e1d1a1c1c20242e2720222c231c1c2837292c30313434341f27393d38323c2e333432ffc00011080001000101011100ffc40014000100000000000000000000000000000000000000ffc400141001000000000000000000000000000000000000000000ffda000c03010002110311003f00f9c000ffd9"))')
GV.append('                    existing.append(path)')
GV.append('        if hasattr(Config, "VIDEO_DIR"):')
GV.append('            video_dir = Path(Config.VIDEO_DIR) / ("product_" + str(product_id))')
GV.append('        else:')
GV.append('            video_dir = Path(__file__).resolve().parent.parent / "output" / "videos" / ("product_" + str(product_id))')
GV.append('        video_dir.mkdir(parents=True, exist_ok=True)')
GV.append('        out_path = video_dir / ("task_" + datetime.now().strftime("%Y%m%d_%H%M%S") + ".mp4")')
GV.append('        concat_txt = video_dir / ("concat_" + str(product_id) + ".txt")')
GV.append('        with open(concat_txt, "w", encoding="utf-8") as _cf:')
GV.append('            for p in existing:')
GV.append('                _s = str(p).replace(chr(39), chr(39) + chr(92) + chr(39) + chr(39))')
GV.append('                _cf.write("file " + chr(39) + _s + chr(39) + chr(10))')
GV.append('                _cf.write("duration 2" + chr(10))')
GV.append('        video_url = None')
GV.append('        thumb_url = None')
GV.append('        tried_ffmpeg = False')
GV.append('        ffmpeg_error = None')
GV.append('        ffmpeg_path = shutil.which("ffmpeg")')
GV.append('        if ffmpeg_path:')
GV.append('            tried_ffmpeg = True')
GV.append('            try:')
GV.append('                cmd = [ffmpeg_path, "-y", "-hide_banner", "-loglevel", "error", "-f", "concat", "-safe", "0", "-i", str(concat_txt), "-pix_fmt", "yuv420p", "-vcodec", "libx264", "-r", "30", str(out_path)]')
GV.append('                proc = subprocess.run(cmd, capture_output=True, text=True, timeout=120)')
GV.append('                if proc.returncode == 0 and out_path.exists() and out_path.stat().st_size > 0:')
GV.append('                    video_url = "/videos/product_" + str(product_id) + "/" + out_path.name')
GV.append('                    thumb_url = "/images/product_" + str(product_id) + "/img_0.jpg"')
GV.append('                else:')
GV.append('                    ffmpeg_error = proc.stderr or "ffmpeg no output"')
GV.append('            except Exception as _e_ffmpeg:')
GV.append('                ffmpeg_error = str(_e_ffmpeg)')
GV.append('        if not video_url:')
GV.append('            video_url = "/images/product_" + str(product_id) + "/img_0.jpg"')
GV.append('            thumb_url = "/images/product_" + str(product_id) + "/img_0.jpg"')
GV.append('        return {')
GV.append('            "success": True, "video_url": video_url, "thumbnail": thumb_url,')
GV.append('            "duration": duration, "product_title": title, "template": template,')
GV.append('            "used_ffmpeg": tried_ffmpeg and (ffmpeg_error is None), "ffmpeg_error": ffmpeg_error,')
GV.append('        }')
GV.append('    except HTTPException:')
GV.append('        raise')
GV.append('    except Exception as e:')
GV.append('        logger.error("generate_video_action failed: " + str(e))')
GV.append('        raise HTTPException(status_code=500, detail={"error": str(e)})')

GENERATE_VIDEO = NL.join(GV)

try:
    ast.parse(GENERATE_VIDEO)
    print("[OK] generate_video_action 语法检查通过")
except SyntaxError as e:
    print("[FAIL] generate_video_action:", e, "行号:", e.lineno)
    around = GENERATE_VIDEO.split(NL)
    for k in range(max(0, e.lineno-3), min(len(around), e.lineno+2)):
        print("  L" + str(k+1) + ": " + around[k])
    sys.exit(1)

# ---------- 现在替换到 routes.py ----------
# 恢复原始
subprocess_run = __import__('subprocess')
subprocess_run.run(['git', 'checkout', '--', 'api/routes.py'], cwd='/workspace', check=True)

routes_path = Path("/workspace/api/routes.py")
content = routes_path.read_text(encoding="utf-8")

# 找到旧的 generate_content_action 并替换
lines = content.split(NL)
new_lines = []
i = 0
n = len(lines)
cg_inserted = False

while i < n:
    if 'actions/generate_content' in lines[i] and '@api_router' in lines[i]:
        # 跳过旧函数，直到找到下一个 @api_router 或 # ----------
        j = i + 1
        while j < n:
            s = lines[j].lstrip()
            if s.startswith('@api_router.post(') or s.startswith('@api_router.get('):
                break
            if s.startswith('# ============') and j > i + 5:
                break
            j += 1
        # 先插入 ContentGenerator，再插入新的 generate_content_action
        if not cg_inserted:
            new_lines.append('')
            new_lines.append('# ============ 本地文案生成兜底（不依赖 LLM） ============')
            new_lines.append('')
            new_lines.append(CONTENT_GENERATOR)
            new_lines.append('')
            new_lines.append('')
            new_lines.append('# ---------- POST /api/actions/generate_content ----------')
            new_lines.append('')
            new_lines.append(GENERATE_CONTENT)
            new_lines.append('')
            cg_inserted = True
        i = j
        continue
    else:
        new_lines.append(lines[i])
        i += 1

if not cg_inserted:
    new_lines.append('')
    new_lines.append('# ============ 本地文案生成兜底（不依赖 LLM） ============')
    new_lines.append('')
    new_lines.append(CONTENT_GENERATOR)
    new_lines.append('')
    new_lines.append('# ---------- POST /api/actions/generate_content ----------')
    new_lines.append('')
    new_lines.append(GENERATE_CONTENT)

# 添加 generate_video_action 到文件末尾
new_lines.append('')
new_lines.append('# ---------- POST /api/actions/generate_video ----------')
new_lines.append('')
new_lines.append(GENERATE_VIDEO)
new_lines.append('')

final_content = NL.join(new_lines)

try:
    ast.parse(final_content)
    print("[OK] 最终 routes.py 语法检查通过")
except SyntaxError as e:
    print("[FAIL] 最终 routes.py 语法错误:", e, "行号:", e.lineno)
    around = final_content.split(NL)
    for k in range(max(0, e.lineno-3), min(len(around), e.lineno+3)):
        print("  L" + str(k+1) + ": " + around[k])
    sys.exit(1)

routes_path.write_text(final_content, encoding="utf-8")
print("[DONE] 写入 api/routes.py 成功，总大小:", routes_path.stat().st_size, "bytes")
