import { n as EventUnsubscribe, r as EventsMap, t as EventEmitter } from "./events-BTCXlxeC.js";
import { $ as ClientScriptEntry, A as DevToolsDocksUserSettings, At as DevToolsLogEntryInput, B as DevToolsNodeUtils, Ct as DevToolsCommandsHost, D as EntriesToObject, Dt as DevToolsLogElementPosition, E as PluginWithDevTools, Et as DevToolsServerCommandInput, F as RpcSharedStateGetOptions, Ft as DevToolsLogsHost, G as DevToolsTerminalHost, H as DevToolsViewHost, I as RpcSharedStateHost, J as DevToolsTerminalSessionStreamChunkEvent, K as DevToolsTerminalSession, L as ConnectionMeta, M as DevToolsNodeRpcSessionMeta, Mt as DevToolsLogHandle, N as RpcBroadcastOptions, Nt as DevToolsLogLevel, O as PartialWithoutId, Ot as DevToolsLogEntry, P as RpcFunctionsHost, Pt as DevToolsLogsClient, Q as DevToolsRpcSharedStates, R as DevToolsCapabilities, St as DevToolsCommandShortcutOverrides, T as RpcDefinitionsToFunctions, Tt as DevToolsServerCommandEntry, U as DevToolsChildProcessExecuteOptions, V as DevToolsPluginOptions, W as DevToolsChildProcessTerminalSession, X as DevToolsRpcClientFunctions, Y as DevToolsTerminalStatus, Z as DevToolsRpcServerFunctions, _t as DevToolsClientCommand, at as DevToolsDockHost, bt as DevToolsCommandHandle, ct as DevToolsViewBuiltin, dt as DevToolsViewJsonRender, et as DevToolsDockEntriesGrouped, ft as DevToolsViewLauncher, gt as JsonRenderer, ht as JsonRenderSpec, it as DevToolsDockEntryIcon, j as DevToolsNodeRpcSession, jt as DevToolsLogFilePosition, k as Thenable, kt as DevToolsLogEntryFrom, lt as DevToolsViewCustomRender, mt as JsonRenderElement, nt as DevToolsDockEntryBase, ot as DevToolsDockUserEntry, pt as DevToolsViewLauncherStatus, q as DevToolsTerminalSessionBase, rt as DevToolsDockEntryCategory, st as DevToolsViewAction, tt as DevToolsDockEntry, ut as DevToolsViewIframe, vt as DevToolsCommandBase, w as RpcDefinitionsFilter, wt as DevToolsCommandsHostEvents, xt as DevToolsCommandKeybinding, yt as DevToolsCommandEntry, z as DevToolsNodeContext } from "./index-BOolwltO.js";
import { t as WhenContext } from "./when-snfIizvo.js";
import * as _$_vitejs_devtools_rpc0 from "@vitejs/devtools-rpc";

//#region src/define.d.ts
declare const defineRpcFunction: <NAME extends string, TYPE extends _$_vitejs_devtools_rpc0.RpcFunctionType, ARGS extends any[], RETURN = void, const AS extends _$_vitejs_devtools_rpc0.RpcArgsSchema | undefined = undefined, const RS extends _$_vitejs_devtools_rpc0.RpcReturnSchema | undefined = undefined>(definition: _$_vitejs_devtools_rpc0.RpcFunctionDefinition<NAME, TYPE, ARGS, RETURN, AS, RS, DevToolsNodeContext>) => _$_vitejs_devtools_rpc0.RpcFunctionDefinition<NAME, TYPE, ARGS, RETURN, AS, RS, DevToolsNodeContext>;
declare function defineCommand(command: DevToolsServerCommandInput): DevToolsServerCommandInput;
declare function defineJsonRenderSpec(spec: JsonRenderSpec): JsonRenderSpec;
//#endregion
export { ClientScriptEntry, ConnectionMeta, DevToolsCapabilities, DevToolsChildProcessExecuteOptions, DevToolsChildProcessTerminalSession, DevToolsClientCommand, DevToolsCommandBase, DevToolsCommandEntry, DevToolsCommandHandle, DevToolsCommandKeybinding, DevToolsCommandShortcutOverrides, DevToolsCommandsHost, DevToolsCommandsHostEvents, DevToolsDockEntriesGrouped, DevToolsDockEntry, DevToolsDockEntryBase, DevToolsDockEntryCategory, DevToolsDockEntryIcon, DevToolsDockHost, DevToolsDockUserEntry, DevToolsDocksUserSettings, DevToolsLogElementPosition, DevToolsLogEntry, DevToolsLogEntryFrom, DevToolsLogEntryInput, DevToolsLogFilePosition, DevToolsLogHandle, DevToolsLogLevel, DevToolsLogsClient, DevToolsLogsHost, DevToolsNodeContext, DevToolsNodeRpcSession, DevToolsNodeRpcSessionMeta, DevToolsNodeUtils, DevToolsPluginOptions, DevToolsRpcClientFunctions, DevToolsRpcServerFunctions, DevToolsRpcSharedStates, DevToolsServerCommandEntry, DevToolsServerCommandInput, DevToolsTerminalHost, DevToolsTerminalSession, DevToolsTerminalSessionBase, DevToolsTerminalSessionStreamChunkEvent, DevToolsTerminalStatus, DevToolsViewAction, DevToolsViewBuiltin, DevToolsViewCustomRender, DevToolsViewHost, DevToolsViewIframe, DevToolsViewJsonRender, DevToolsViewLauncher, DevToolsViewLauncherStatus, EntriesToObject, EventEmitter, EventUnsubscribe, EventsMap, JsonRenderElement, JsonRenderSpec, JsonRenderer, PartialWithoutId, PluginWithDevTools, RpcBroadcastOptions, RpcDefinitionsFilter, RpcDefinitionsToFunctions, RpcFunctionsHost, RpcSharedStateGetOptions, RpcSharedStateHost, Thenable, WhenContext, defineCommand, defineJsonRenderSpec, defineRpcFunction };