import { PointerEventType } from './DragTracker';
import { NumberStoreType } from './NumberStore';
export type WindowType = Window & typeof globalThis;
export type NumberStoreInputType = NumberStoreType | number;
export declare function mapStoreToNumber<ReturnType>(callback: (input: number) => ReturnType): (input: NumberStoreInputType) => ReturnType;
export declare function isNumber(subject: unknown): subject is number;
export declare function isString(subject: unknown): subject is string;
export declare function isBoolean(subject: unknown): subject is boolean;
export declare function isObject(subject: unknown): subject is Record<string, unknown>;
export declare function mathAbs(input: number): number;
export declare function mathSign(input: number): number;
export declare function deltaAbs(inputB: number, inputA: number): number;
export declare function factorAbs(inputB: number, inputA: number): number;
export declare function roundToTwoDecimals(input: number): number;
export declare function arrayKeys<Type>(array: Type[]): number[];
export declare function arrayLast<Type>(array: Type[]): Type;
export declare function arrayLastIndex<Type>(array: Type[]): number;
export declare function arrayIsLastIndex<Type>(array: Type[], index: number): boolean;
export declare function arrayFromRange(end: number, start?: number): number[];
export declare function objectKeys<Type extends object>(object: Type): string[];
export declare function objectsMergeDeep(objectA: Record<string, unknown>, objectB: Record<string, unknown>): Record<string, unknown>;
export declare function isMouseEvent(evt: PointerEventType, ownerWindow: WindowType): evt is MouseEvent;
