declare const pedanticRules: Record<string, 'off'>;
declare const styleRules: Record<string, 'off'>;
declare const suspiciousRules: Record<string, 'off'>;
declare const restrictionRules: Record<string, 'off'>;
declare const correctnessRules: Record<string, 'off'>;
declare const nurseryRules: Record<string, 'off'>;
declare const perfRules: Record<string, 'off'>;
declare const correctnessTypeAwareRules: Record<string, 'off'>;
declare const suspiciousTypeAwareRules: Record<string, 'off'>;
declare const styleTypeAwareRules: Record<string, 'off'>;
declare const pedanticTypeAwareRules: Record<string, 'off'>;
declare const nurseryTypeAwareRules: Record<string, 'off'>;
declare const restrictionTypeAwareRules: Record<string, 'off'>;
export { pedanticRules, styleRules, suspiciousRules, restrictionRules, correctnessRules, nurseryRules, perfRules, correctnessTypeAwareRules, suspiciousTypeAwareRules, styleTypeAwareRules, pedanticTypeAwareRules, nurseryTypeAwareRules, restrictionTypeAwareRules, };
