import { AnimationsType } from './Animations.js';
import { AxisType } from './Axis.js';
import { CounterType } from './Counter.js';
import { DragHandlerType } from './DragHandler.js';
import { EventHandlerType } from './EventHandler.js';
import { EventStoreType } from './EventStore.js';
import { LimitType } from './Limit.js';
import { NodeRectsType, NodeRectType } from './NodeHandler.js';
import { OptionsType } from './Options.js';
import { PercentOfViewType } from './PercentOfView.js';
import { ResizeHandlerType } from './ResizeHandler.js';
import { ScrollBodyType } from './ScrollBody.js';
import { ScrollBoundsType } from './ScrollBounds.js';
import { ScrollLooperType } from './ScrollLooper.js';
import { ScrollProgressType } from './ScrollProgress.js';
import { ScrollSnapListType } from './ScrollSnapList.js';
import { ScrollTargetType } from './ScrollTarget.js';
import { ScrollToType } from './ScrollTo.js';
import { SlideFocusType } from './SlideFocus.js';
import { SlideLooperType } from './SlideLooper.js';
import { SlidesHandlerType } from './SlidesHandler.js';
import { SlidesInViewType } from './SlidesInView.js';
import { SlidesToScrollType } from './SlidesToScroll.js';
import { TranslateType } from './Translate.js';
import { NumberStoreType } from './NumberStore.js';
import { NodeHandlerType } from './NodeHandler.js';
import { ScrollOptimizerType } from './ScrollOptimizer.js';
export type EngineType = {
    isSsr: boolean;
    eventHandler: EventHandlerType;
    contentSize: number;
    axis: AxisType;
    animation: AnimationsType;
    scrollBounds: ScrollBoundsType;
    scrollLooper: ScrollLooperType;
    scrollProgress: ScrollProgressType;
    indexCurrent: CounterType;
    indexPrevious: CounterType;
    limit: LimitType;
    location: NumberStoreType;
    offsetLocation: NumberStoreType;
    previousLocation: NumberStoreType;
    options: OptionsType;
    percentOfView: PercentOfViewType;
    scrollBody: ScrollBodyType;
    dragHandler: DragHandlerType;
    eventStore: EventStoreType;
    slideLooper: SlideLooperType;
    slidesInView: SlidesInViewType;
    slidesToScroll: SlidesToScrollType;
    target: NumberStoreType;
    translate: TranslateType;
    slideTranslates: TranslateType[];
    resizeHandler: ResizeHandlerType;
    slidesHandler: SlidesHandlerType;
    nodeHandler: NodeHandlerType;
    scrollTo: ScrollToType;
    scrollTarget: ScrollTargetType;
    scrollSnaps: number[];
    slideIndexes: number[];
    scrollOptimizer: ScrollOptimizerType;
    slideSizes: number[];
    slideFocus: SlideFocusType;
    scrollSnapList: ScrollSnapListType;
    containerRect: NodeRectType;
    slideRects: NodeRectType[];
};
export declare function Engine(root: HTMLElement, container: HTMLElement, slides: HTMLElement[], options: OptionsType, nodeHandler: NodeHandlerType, eventHandler: EventHandlerType, rects: NodeRectsType, isSsr: boolean): EngineType;
