import { PostHog } from '../../posthog-core';
import { ProductTour, ProductTourCallback, ProductTourDismissReason, ProductTourRenderReason } from '../../posthog-product-tours-types';
export declare class ProductTourManager {
    private _instance;
    private _activeTour;
    private _currentStepIndex;
    private _renderReason;
    private _checkInterval;
    private _triggerSelectorListeners;
    private _surveyEventUnsubscribe;
    constructor(instance: PostHog);
    start(): void;
    stop(): void;
    private _handleVisibilityChange;
    private _evaluateAndDisplayTours;
    private _isTourEligible;
    showTour(tour: ProductTour, reason?: ProductTourRenderReason): void;
    showTourById(tourId: string): void;
    nextStep: () => void;
    previousStep: () => void;
    dismissTour: (reason?: ProductTourDismissReason) => void;
    private _completeTour;
    private _renderCurrentStep;
    private _renderTooltipWithPreact;
    private _renderSurveyStep;
    private _cleanupSurveyListener;
    private _cleanup;
    private _manageTriggerSelectorListener;
    private _removeTriggerSelectorListener;
    private _removeAllTriggerListeners;
    private _captureEvent;
    getActiveProductTours(callback: ProductTourCallback): void;
    resetTour(tourId: string): void;
    resetAllTours(): void;
}
