import { AnimationsType } from './Animations';
import { AxisType } from './Axis';
import { CounterType } from './Counter';
import { DragHandlerType } from './DragHandler';
import { EventHandlerType } from './EventHandler';
import { EventStoreType } from './EventStore';
import { LimitType } from './Limit';
import { NodeRectsType, NodeRectType } from './NodeHandler';
import { OptionsType } from './Options';
import { PercentOfViewType } from './PercentOfView';
import { ResizeHandlerType } from './ResizeHandler';
import { ScrollBodyType } from './ScrollBody';
import { ScrollBoundsType } from './ScrollBounds';
import { ScrollLooperType } from './ScrollLooper';
import { ScrollProgressType } from './ScrollProgress';
import { ScrollSnapListType } from './ScrollSnapList';
import { ScrollTargetType } from './ScrollTarget';
import { ScrollToType } from './ScrollTo';
import { SlideFocusType } from './SlideFocus';
import { SlideLooperType } from './SlideLooper';
import { SlidesHandlerType } from './SlidesHandler';
import { SlidesInViewType } from './SlidesInView';
import { SlidesToScrollType } from './SlidesToScroll';
import { TranslateType } from './Translate';
import { NumberStoreType } from './NumberStore';
import { NodeHandlerType } from './NodeHandler';
import { ScrollOptimizerType } from './ScrollOptimizer';
export type EngineType = {
    isSsr: boolean;
    eventHandler: EventHandlerType;
    contentSize: number;
    axis: AxisType;
    animation: AnimationsType;
    scrollBounds: ScrollBoundsType;
    scrollLooper: ScrollLooperType;
    scrollProgress: ScrollProgressType;
    indexCurrent: CounterType;
    indexPrevious: CounterType;
    limit: LimitType;
    location: NumberStoreType;
    offsetLocation: NumberStoreType;
    previousLocation: NumberStoreType;
    options: OptionsType;
    percentOfView: PercentOfViewType;
    scrollBody: ScrollBodyType;
    dragHandler: DragHandlerType;
    eventStore: EventStoreType;
    slideLooper: SlideLooperType;
    slidesInView: SlidesInViewType;
    slidesToScroll: SlidesToScrollType;
    target: NumberStoreType;
    translate: TranslateType;
    slideTranslates: TranslateType[];
    resizeHandler: ResizeHandlerType;
    slidesHandler: SlidesHandlerType;
    nodeHandler: NodeHandlerType;
    scrollTo: ScrollToType;
    scrollTarget: ScrollTargetType;
    scrollSnaps: number[];
    slideIndexes: number[];
    scrollOptimizer: ScrollOptimizerType;
    slideSizes: number[];
    slideFocus: SlideFocusType;
    scrollSnapList: ScrollSnapListType;
    containerRect: NodeRectType;
    slideRects: NodeRectType[];
};
export declare function Engine(root: HTMLElement, container: HTMLElement, slides: HTMLElement[], options: OptionsType, nodeHandler: NodeHandlerType, eventHandler: EventHandlerType, rects: NodeRectsType, isSsr: boolean): EngineType;
