export default rules;
declare const rules: {
    readonly "markdown/fenced-code-language": "error";
    readonly "markdown/heading-increment": "error";
    readonly "markdown/no-duplicate-definitions": "error";
    readonly "markdown/no-empty-definitions": "error";
    readonly "markdown/no-empty-images": "error";
    readonly "markdown/no-empty-links": "error";
    readonly "markdown/no-invalid-label-refs": "error";
    readonly "markdown/no-missing-atx-heading-space": "error";
    readonly "markdown/no-missing-label-refs": "error";
    readonly "markdown/no-missing-link-fragments": "error";
    readonly "markdown/no-multiple-h1": "error";
    readonly "markdown/no-reference-like-urls": "error";
    readonly "markdown/no-reversed-media-syntax": "error";
    readonly "markdown/no-space-in-emphasis": "error";
    readonly "markdown/no-unused-definitions": "error";
    readonly "markdown/require-alt-text": "error";
    readonly "markdown/table-column-count": "error";
};
